# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=rst]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [-l 120]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
    hooks:
    -   id: isort
        args: [ --filter-files ]
