language: python
cache: pip
python:
- 3.8
- 3.7
- 3.6
install:
    - pip install -U pip tox-travis
script: tox -v
deploy:
  provider: pypi
  edge: true
  distributions: sdist bdist_wheel
  user: griano
  password: $PYPI_PASSWORD
  on:
    tags: true
    repo: griano/epistoch
    python: 3.8
