language: python
python:
- 3.8
- 3.7
- 3.6
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - pip install -U tox-travis

script: tox -v --parallel
deploy:
  provider: pypi
  edge: true
  distributions: sdist bdist_wheel
  user: griano
  password: $PYPI_PASSWORD
  on:
    tags: true
    repo: griano/epistoch
    python: 3.8
